### PR TITLE
Add Card.FilterEffect & Duel.FilterPlayerEffect

### PR DESCRIPTION
**Pull request by purerosefallen**
... Card.FilterEffect(card c, int code)
will return all the effects card c affected, which would be easy to check the effects like EFFECT_CANNOT_BE_XYZ_MATERIAL or sth else.

Duel.FilterPlayerEffect(int player, int code)
similar to Duel.IsPlayerAffectedByEffect, but also returns all the effects of a player

### CODE REVIEW

**Comment by edo9300** [comment]
Wow, appaerently you had my same idea ;), even if my gunction is alled GetPlayer/CardEffect

**Comment by purerosefallen** [comment]
This one is actually from KoishiPRO

**Comment by Zayelion** [comment]
What is KoishiPRO?

**Comment by edo9300** [comment]
Probably his client, ~~like edopro for me~~

**Comment by purerosefallen** [comment]
The client used in 222 and YGOCC

**Comment by mercury233** [comment]
So any example in card script?

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/c4e0a851dd8433c2aa165ba0d5666aa99aa4b93e

**Pull request closed without merging**
