### PR TITLE
update Duel.CheckReleaseGroup

### PR DESCRIPTION
**Pull request by mercury233**
before:
```lua
	if sg:GetCount()>0 and Duel.GetMZoneCount(tp,sg)>0 then
		Duel.SetSelectedCard(sg)
		return Duel.CheckReleaseGroup(tp,nil,0,nil)
	else return false end
```
after:
```lua
	return sg:GetCount()>0 and Duel.GetMZoneCount(tp,sg)>0 and Duel.CheckReleaseGroup(tp,sg,#sg,nil)
```

### CODE REVIEW

**Comment by DailyShana** [comment]
it's misleading, Duel.CheckReleaseGroup(tp,sg,0,nil) means check 0 monsters from sg?

**Comment by mercury233** [comment]
means can release sg and 0 other monster

**Comment by DailyShana** [comment]
`Duel.CheckReleaseGroup(tp,filter,count,nil)` means is there exists `count` monster satisfying filter to release, so it is nature to expect that `Duel.CheckReleaseGroup(tp,group,count,nil)` means is there exists `count` monster in `group` to release.
It's inappropriate that a parameter has different meaning in two overloads.

**Comment by mercury233** [comment]
@DailyShana it is updated to use `Duel.CheckReleaseGroup(tp,sg,#sg,nil)` now

**Comment by DailyShana** [comment]
I think this way is enough
```lua
function filter(c,sg)
    return sg:IsContains(c)
end

return sg:GetCount()>0 and Duel.GetMZoneCount(tp,sg)>0 and Duel.CheckReleaseGroup(tp,filter,#sg,sg)
```

**Comment by mercury233** [comment]
should it be `Duel.CheckReleaseGroup(tp,filter,#sg,nil,sg)` ?

**Comment by DailyShana** [comment]
yes, it's a little mistake

**Pull request closed without merging**
