### PR TITLE
update premake5 & basic support for lua5.4

### PR DESCRIPTION
**Pull request by mercury233**
https://github.com/Fluorohydride/ygopro-core/pull/326
https://github.com/Fluorohydride/ygopro-core/issues/337

### CODE REVIEW

**Comment by mercury233** [comment]
The lua5.4 part had been tested in my server

**Comment by mercury233** [comment]
some `PANIC: unprotected error in call to Lua API (attempt to call a nil value)` appears, it seems some errors aren't handled by the core

**Comment by mercury233** [comment]
@salix5 I think the lua5.4 part can be merged, and it cant make the premake system of ygopro worse because it is messed up already.

**Comment by salix5** [comment]
> some `PANIC: unprotected error in call to Lua API (attempt to call a nil value)` appears, it seems some errors aren't handled by the core

Is this fixed now?

**Comment by mercury233** [comment]
> > some `PANIC: unprotected error in call to Lua API (attempt to call a nil value)` appears, it seems some errors aren't handled by the core
> 
> Is this fixed now?

no, i didn't find how to reproduce

**Comment by salix5** [comment]
Just want to confirm because I don't understand

Is there any advantage in moving to Lua 5.4?

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-core/pull/326#issuecomment-669069688

**Comment by mercury233** [comment]
There are something wrong with `lua_settop`(called by `lua_pop` in https://github.com/Fluorohydride/ygopro-core/blob/master/operations.cpp#L5197) and the new feature to-be-closed variable, will check that later.

**Pull request merged**
