### PR TITLE
update Duel.SelectDisableField for extra mzone

### PR DESCRIPTION
**Pull request by purerosefallen**

### CODE REVIEW

**Comment by DailyShana** [comment]
it's better to allow selecting extra mzone automatically when `filter` parameter contains bits for extra mzone

**Comment by purerosefallen** [comment]
@DailyShana `filter` is a bit for the zone NOT selectable. So it's not very proper to use `filter` for extra zones.

**Comment by DailyShana** [comment]
it natural to use `filter` to decide which zone is selectable, for cards that cannot select extra moster zone, just make a little modify

**Comment by purerosefallen** [comment]
*Making announcements is painful*

**Pull request closed without merging**
