### PR TITLE
Added IsLevel/Rank/Link

### PR DESCRIPTION
**Pull request by edo9300**
Those are basic functions, and it's very weird they had not yet been added....

### CODE REVIEW

**Comment by DailyShana** [comment]
They are redundant because there are GetLevel, GetRank and GetLink.

**Comment by edo9300** [comment]
Well, wouldn't is better to write `Duel.GetMatchingGroup(Card.IsLevel,tp,loc,loc,nil,lv)` instead of using the aux function and write `Duel.GetMatchingGroup( aux.FilterEqualFunction(Card.GetLevel,lv),tp,loc,loc,nil)`?

**Comment by DailyShana** [comment]
It think that's enough for usage.

**Comment by mercury233** [comment]
Easier is better

**Pull request merged**
