### PR TITLE
Correct Warning C4267 in Visual Studio

### PR DESCRIPTION
**Pull request by Zayelion**
Steps to reproduce:
- 1.) Download Source
- 2.) Add missing libs
- 3.) `premake4 vs2013`
- 4.) Compile `ocgcore` project for `x86` both `Debug` and `Release`

Expected result is a clean compile, result is [C4244](https://msdn.microsoft.com/en-us/library/th7a07tz.aspx) warnings in most the files.

I dont think this "adds" anything to the codebase but less warnings is always better I personally feel.

### CODE REVIEW

**Comment by IceYGO** [comment]
:+1: Looks good to me.

Would be even better using the C++ `static_cast<>` instead.

**Comment by Zayelion** [comment]
@salix5 take a look?

**Comment by salix5** [comment]
I'm searching for data about C4244

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-core/blob/master/common.h#L12

**Comment by Zayelion** [comment]
I removed the line in `common.h` and got a new but similar set of errors. Is there any type of value gained by ignoring this warning?

**Comment by DailyShana** [comment]
>to ensure that the range of possible values will always be compatible with the types you are using.

All these integers will not exceed the max value of uint8 actually(bounded by the size of deck)

**Comment by Zayelion** [comment]
That may happen to be the case now, but the ultimate check for it if any of the code is changed else where is turned off. Just seems unsafe to me. I feel while its could be seen as only stylistic it helps the overall longevity of the code base for newer developers to correct it.

**Comment by DailyShana** [comment]
Complile warning just remind it is possible sth would happen but we know that sth will not happen so it is meaningless to consider it and closing that warning is safe.

**Comment by IceYGO** [comment]
Disabling warnings is stupid.

Yes, maybe the current code is safe. But how can we be sure? What if we change something? What if we add more code?

**Comment by DailyShana** [comment]
Explicit type conversion/cast do not reduce the risk of data loss, it just disable the warning of that line of the code.
It is no difference between disabling warning and explicit conversion.

It's clear that data loss cannot happen here because all size of these volumes is bounded by the size of deck and if it really happened, we should reconstruct the code, not just use type conversion/cast.

We don't need to worry about this and should focus on the logic of rule and card effects.

**Comment by IceYGO** [comment]
Explicit type conversion will, as you said, explicitly says to the 
compiler "I know what I am doing here".
It is entirely different than disabling the warning everywhere, telling 
to the compiler "Do not check my entire code".

Again, if we add some code causing an error because of an implicit type 
conversion someday, we will be glad if the compiler tells us where it 
comes from. It's not just about this code, it's about good habits.

**Comment by DailyShana** [comment]
The result of explicit type conversion and disable warning is the same.
"I know what I am doing here, so do not check my entire code"

**Comment by IceYGO** [comment]
If everyone working on the project is absolutely certain that the entire 
code (current and future) will never have any problem caused by an 
implicit cast, then yes, you can keep this line.

**Comment by Zayelion** [comment]
Im not certain, Im learning C++ by working on this project. The change I'm suggesting are just code clean up. I was taught as code becomes stable to clean up parts of it. Its also open source we dont know what type of people and of what skill level they will be joining the project.

The code changes I did are causing a higher level warning than what that line of code is suppressing. (It doesnt seem smart to suppress errors to me, it seems smart to fix them).

At the moment I cant do the major code changes I want to do so as I'm learning Im personally just focusing on making the flow of code less complex for people reading it. From looking at it myself and other professional I've asked the opinion of and comparing it to other C++ projects the overall code base is very much a mess.

**Comment by Zayelion** [comment]
Is this gonna be merged or rejected? Letting it sit here to bit rot is not particularly polite.

**Comment by salix5** [comment]
Sorry for the late reply.
Since I have very limited time now, I am afraid that I can only check changes that directly related to card or system bugs.

**Comment by Zayelion** [comment]
... Then could someone else press the button?

**Comment by DailyShana** [comment]
fixed in e6ac7e88b247a917a9427ebb9334a1921be98c22

**Pull request closed without merging**
