### PR TITLE
[WIP] set equip/continuous target before chain solving

### PR DESCRIPTION
**Pull request by DailyShana**
for Fluorohydride/ygopro#2254

### CODE REVIEW

**Comment by nekrozar** [comment]
If _Cubic Karma_'s activate solved, _Cubic Karma_ keep target.

**Comment by salix5** [comment]
This version will raise and process EVENT_EQUIP before operation function executes, and it could be wrong in some soecial cases.
Ex. 
The operation function of equip card special summons/flips new monster cards.
Their EVENT_EQUIP effects should be processed after the operation function finishes.

原版：
腳本通常是在執行完其他動作之後，最後呼叫Duel.Equip()
因此EVENT_EQUIP會在裝備魔法卡的operation結束後觸發

新版：
在裝備魔法卡的operation執行之前處理EVENT_EQUIP事件
可能會漏掉在執行operation以後可以觸發的誘發效果
例如在operation裡面特殊召喚/翻開的怪獸

**Comment by DailyShana** [comment]
This change do not affect cards like _Premature Burial_

**Comment by salix5** [comment]
即使是以場上1隻怪獸為對象的裝備魔法卡
一樣可以在發動時的效果處理特殊召喚或翻開場上的卡
他們的EVENT_EQUIP處理順序應該要和早埋一樣

**Comment by DailyShana** [comment]
First equip to some monster, then special summon a monster that have effect with EVENT_EQUIP, range LOCATION_MZONE. This effect of cause cannot be activated.

**Comment by DailyShana** [comment]
This approach seems lack of flexibility, some equip card or continuous spell/trap need to do some other things like registering some effect after setting equip/continuous target.

**Pull request closed without merging**
