### PR TITLE
Old master rule compatibilities

### PR DESCRIPTION
**Pull request by edo9300**
@DailyShana since you started already working on the new changes, i don't think there's stuff left to change (i already tested the changes and seem ok), so just to help a little i added the checks for the master rules to keep the old behaviours intact.

### CODE REVIEW

**Comment by DailyShana** [comment]
These two changes are just the normal ruling change, which happened many times in the past.
And the changes much simplfy the rule thus the implement is simplified structurally. It's hard to split into old ones or new ones, like the new damage step rule in master rule 3, or the end phase rule change long ago.

**Comment by edo9300** [comment]
Idk, I still see them as changes introduced by the master rule. For the split, this scenario doesn't seem to drastically change the structure in such a way that it prevents it to coexist, bit I kinda see that there could be possible issues in case the handling for the conditions is reworked in the core and this would make that rework more tedious as it'll have to address these "compatibility layers"

**Comment by purerosefallen** [comment]
Just reworked this PR as a PR to master...

**Comment by DailyShana** [comment]
old trigger effect ruling has added back.
since old rulings about special summon count is complicated (eg. the rule of rage with eyes of blue+a negated summon has been changed in 2018.06)
and the code is full of working around, this part will not add back

**Pull request closed without merging**
