### PR TITLE
update discard

### PR DESCRIPTION
**Pull request by nekrozar**
for _Guiding Ariadne_ and _Witchcrafter_.
- add function `Duel.GetDiscardHand`, `Duel.GetDiscardHandCount`, `Duel.GetDiscardHandChangeCount`, `Duel.CheckDiscardHand`, `Duel.DiscardHandStep` and `Duel.DiscardHandComplete`.
- add constant `EFFECT_DISCARD_HAND_CHANGE` and `EFFECT_DISCARD_HAND_REPLACE`
- update `Duel.DiscardHand`.
- remove `EFFECT_DISCARD_COST_CHANGE`.

### CODE REVIEW

**Comment by DailyShana** [comment]
I think the `EFFECT_DISCARD_HAND_CHANGE` is over consideration, we can't predict what kind of effect will appear.
just use it as `EFFECT_AVOID_DISCARD_HAND` to keep reflexivity.

and the interation of `EFFECT_DISCARD_HAND_REPLACE` and _Linkslayer_ is also unknown
It's better add things like `Duel.CheckHandDiscardChange` only when necessary

In fact, for special effects used in a small around of cards, it's better to add only necessary functions and new effect types,
and wait for these kind of effects become generic because too much things is unknown.

**Comment by nekrozar** [comment]
closed pull requests.
but
https://github.com/Fluorohydride/ygopro-scripts/pull/1199/commits/a970e1fdd6b1b0f3712808189dde9372487e1689
_Goblin of Greed_ and _F.A. Whip Crosser_ have serious issue, and these issue cannot fix(because _Danger!_ and _Dicelops_ and so on are also unknown).

**Comment by DailyShana** [comment]
the discard hand of _Dicelops_ is not cost, so unaffected by _Goblin of Greed_?

**Comment by nekrozar** [comment]
discard's cost and discard's effect should need check `Card.IsDiscardable`.
however, opponent's hand cannot check `Card.IsDiscardable`.

**Comment by DailyShana** [comment]
I think we can ignore the unknown part and fix the known part

**Comment by nekrozar** [comment]
so, I say "_Goblin of Greed_'s issue and _F.A. Whip Crosser_'s issue cannot fix".

**Comment by DailyShana** [comment]
just check `EFFECT_CANNOT_DISCARD_HAND` only when reason is cost

**Comment by nekrozar** [comment]
maybe you forget _Jurrac Gallim_.

**Comment by DailyShana** [comment]
but it's also not cost

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-core/blob/master/libcard.cpp#L2250
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c43332022.lua#L27

**Comment by DailyShana** [comment]
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c43332022.lua#L28
>Ｑ：相手のこのカードの破壊する効果処理の代わりに手札を捨てた場合、相手のカードの効果により捨てた扱いになりますか？
Ａ：はい、相手のカードの効果により捨てた扱いになり、《暗黒界の武神 ゴルド》の除去効果等が発動します。(09/11/05)
http://yugioh-wiki.net/index.php?%A1%D4%A5%B8%A5%E5%A5%E9%A5%C3%A5%AF%A1%A6%A5%AC%A5%EA%A5%E0%A1%D5#faq

**Pull request closed without merging**
