### PR TITLE
add Card.GetSummonSequence

### PR DESCRIPTION
**Pull request by nekrozar**
for "monster is Special Summoned to a zone" effect.

### CODE REVIEW

**Comment by DailyShana** [comment]
it can be solved in #223
and it is meaningless to think summon infomation of monsters not on field, it causes some problem like Fluorohydride/ygopro#1737

**Comment by nekrozar** [comment]
> and it is meaningless to think summon infomation of monsters not on field, it causes some problem like Fluorohydride/ygopro#1737

Sorry, I couldn't understand this.

**Comment by DailyShana** [comment]
"special summoned from extra deck" is meaningless for monsters in grave.
first special summon some monster from extra, then send it to grave. In other turn use Monster Reborn to special summon it from grave, then The Monarchs Stormforth cannot be activated this turn in ygopro.
this is because that monster has summon_location==LOCATION_EXTRA even in grave

**Comment by nekrozar** [comment]
thanks.
these pull requests close.

**Pull request closed without merging**
