### PR TITLE
add lua-5.4.6.tar.gz to local directory

### PR DESCRIPTION
**Pull request by salix5**
SHA256:
7d5ea1b9cb6aa0b59ca3dde1c6adcb57ef83a1ba8e5432c0ecd06bf439b3ad88

Maybe we should keep a local copy of `lua-5.4.6.tar.gz`.

@mercury233

### CODE REVIEW

**Comment by mercury233** [comment]
I don't agree

**Comment by salix5** [comment]
It seems that Lua 5.4 updates about once per year since 2020.
Why don't we keep a local copy instead of downloading every time?

By the way, we cannot connect to `https://www.lua.org/` now.
So the auto build is currently down.

**Comment by edo9300** [comment]
Lua has tagged releases on their github mirror https://github.com/lua/lua

**Comment by salix5** [comment]
@edo9300 
Thank you!
Now it uses github release in #604 .

**Pull request closed without merging**
