### PR TITLE
add Card.IsCanBeLinkMaterial, Card.GetLinkType and Card.IsLinkType

### PR DESCRIPTION
**Pull request by nekrozar**
https://twitter.com/YuGiOh_OCG_INFO/status/878900574036643840
Deal with the _Mecha Phantom Beast Liten_.

### CODE REVIEW

**Comment by edo9300** [comment]
Wouldn't be better removing the monster type check? We know what happened with fusions and synchros with the last cards, that can use non monsters for a synchro and fusion summon (probably we'll get a similar card for xyzs). So in my opinion it would be better to "prepare" this functions in prevision of this kind of cards.

**Comment by nekrozar** [comment]
@VanillaSalt @DailyShana @mercury233 What do you think of @edo9300 idea?

**Comment by mercury233** [comment]
I think it should be ok to add `card::get_xyz_type` and `card::get_link_type` too.

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-core/pull/98/commits/0f4d4baef4fc26bc617d98198533309b161004d1 updated.
I'll add `card::get_xyz_type` later.

**Pull request merged**
