### PR TITLE
Add an option to make the Player 2 go first

### PR DESCRIPTION
**Pull request by IceYGO**
This is useful in some situations (AI duel, ...) and does not require a lot of changes (3 lines).

### CODE REVIEW

**Comment by DailyShana** [comment]
I think specifying who goes first should be excuted in the server code.
ocgcore only consider the game process.

**Comment by IceYGO** [comment]
I think who goes first is definitely a part of the game process.
Implementing it in the server requires much more code.

On gframe, it is implemented by swapping the players at the beginning of the duel, but it really feels dirty:
https://github.com/Fluorohydride/ygopro/blob/master/gframe/tag_duel.cpp#L324

**Comment by lllyasviel** [comment]
Then maybe there will be a DUEL_PLAYER_2_FIRST_TAG for symmetry.And then there will be more “#define”. If so, we may find it better to let these handled by server code instead of ocgcore.

**Comment by IceYGO** [comment]
Tag duels do not require such change: they are already handled by the server code properly and do not require swapping players.

**Pull request closed without merging**
