### PR TITLE
update `EFFECT_UNRELEASABLE_NONSUM`

### PR DESCRIPTION
**Pull request by Lyris12**
for `Ritual Beast Ulti-Reirautari` (`聖霊獣騎 レイラウタリ`):
* expose reason effect
* add reason support for Tributing cards

### CODE REVIEW

**Comment by salix5** [comment]
How about adding new parameter to `Duel.CheckReleaseGroup`, `Duel.CheckReleaseGroupEx`?

For example:
```lua

---@return boolean
---@param reason integer
---@param player integer
---@param f function|nil
---@param count integer
---@param ex Card|Group|nil
---@param ... any
function Duel.CheckReleaseGroup(reason,player,f,count,ex,...) end
```

**Comment by Lyris12** [comment]
> How about adding new parameter to `Duel.CheckReleaseGroup`, `Duel.CheckReleaseGroupEx`?
> 
> For example:
> 
> ```lua
> ---@return boolean
> ---@param reason integer
> ---@param player integer
> ---@param f function|nil
> ---@param count integer
> ---@param ex Card|Group|nil
> ---@param ... any
> function Duel.CheckReleaseGroup(reason,player,f,count,ex,...) end
> ```

That does not cover cards using only `Duel.GetReleaseGroup` for their costs.

**Comment by salix5** [comment]
Thank you!

To-do-list:
- Duel.CheckReleaseGroup
- Duel.GetReleaseGroup

Is there anything else?

**Comment by salix5** [comment]
#516 
I think we can change these functions.

**Comment by Lyris12** [comment]
Not sure what the `must_param` is for, but that works for me, too!

**Comment by Lyris12** [comment]
..._PROVIDED_ the scripts are updated accordingly, 1st.

**Comment by Lyris12** [comment]
> > Not sure what the `must_param` is for, but that works for me, too!
> 
> The number of necessary parameters.

Ah, gotcha! Thanks!

**Comment by salix5** [comment]
Since it is fixed in #516, this PR will be closed.
Thank you for your help.

**Pull request closed without merging**
