### PR TITLE
new ruling of return to deck and extra

### PR DESCRIPTION
**Pull request by Yuzurisa**

### CODE REVIEW

**Comment by DailyShana** [comment]
wrong implement

**Comment by Yuzurisa** [comment]
I have just pushed some more commits..

**Comment by Yuzurisa** [comment]
Could you tell me your thoughts of this rule changing?

**Comment by DailyShana** [comment]
your change just exclude cards returned to hand/deck/extra from leaving field cards.
this is obviously wrong

**Comment by Yuzurisa** [comment]
Unable to open this PR. Asking for help

**Comment by Yuzurisa** [comment]
@DailyShana what is expected?

**Comment by edo9300** [comment]
> @DailyShana what is expected?

Check the already existing handling for cards returned to the main deck, as basically this new ruling extends this behaviour to the extra deck

**Pull request closed without merging**
