### PR TITLE
add chint to opponent's hand

### PR DESCRIPTION
**Pull request by nekrozar**
automaticity https://github.com/Fluorohydride/ygopro-scripts/commit/ea0e0cb76cb351ea68c37c84f368fdf238b730d2

### CODE REVIEW

**Comment by DailyShana** [comment]
maybe it can be done in `add_card()`?

**Comment by nekrozar** [comment]
@DailyShana If these code moved in `add_card`, ygopro crashed.

**Comment by edo9300** [comment]
@nekrozar what kind of crash? Cannot you follow the call stack and find out the issue?

**Comment by edo9300** [comment]
The crash is happening because MSG_CARD_HINT is being written by add_effect while MSG_MOVE is still being written

**Comment by nekrozar** [comment]
This problem happen in `ClientField::AddCard`.

@edo9300 thanks for find and confirm.

**Pull request merged**
