### PR TITLE
fix dec_count

### PR DESCRIPTION
**Pull request by mercury233**
Fix https://github.com/Fluorohydride/ygopro/issues/2157

### CODE REVIEW

**Comment by mercury233** [comment]
There are some places in codes where directly check `count_limit`, should we change them to `check_count_limit`?
https://github.com/Fluorohydride/ygopro-core/blob/8ec990d52340f20661ad76d7fa6742dc6281a469/operations.cpp#L3159

**Comment by VanillaSalt** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/35927886a1effa6c8a2eccaa1eff2eb84e8595b3
https://github.com/Fluorohydride/ygopro-scripts/commit/97dff7c7692d933ed0cfc94daf71306563edd13d#diff-96167409e082364fb0fa37d4fae353bb

**Comment by mercury233** [comment]
@VanillaSalt Sorry I can't understand what this mean. BTW, cards like `D.D. Seeker` have same problem.

**Comment by VanillaSalt** [comment]
If you merge this fix, you will be able to use Blizzard Falcon's effect during next your turn to use same effect

**Comment by mercury233** [comment]
I forget I once [reported](https://github.com/Fluorohydride/ygopro/issues/1697) this...
Now it should be fixed

**Pull request merged**
