### PR TITLE
small name change

### PR DESCRIPTION
**Pull request by AndreOliveiraMendes**
updated the name.
related with https://github.com/Fluorohydride/ygopro-scripts/pull/1075

### CODE REVIEW

**Comment by mercury233** [comment]
Why is the new name better?

**Comment by edo9300** [comment]
The first name is not correct grammatically, also could be mistaken with the summon from the extra deck, this one is grammatically correct and more intuitive

**Comment by purerosefallen** [comment]
Why not making it return the count

**Comment by AndreOliveiraMendes** [comment]
or probaly either the bool and count?

**Comment by DailyShana** [comment]
Literally, if CheckAdditionalSummon returns true, it should mean the player have not use the chance of extra normal summon and can activate those effects.

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro-core/commit/ce33757015da7334e6883589bc6288a64823f1c0 merged

**Comment by purerosefallen** [comment]
I'm going to remove this function and add a param to Duel.IsPlayerCanSummon.

**Pull request closed without merging**
