### PR TITLE
multiple effect label

### PR DESCRIPTION
**Pull request by DailyShana**
It will be useful for some cards like _Tuner's High_.

### CODE REVIEW

**Comment by purerosefallen** [comment]
`e:SetLabel(c:GetAttack() | c:GetDefense()<<16 | c:GetLevel()<<24 | ...)` may be enough
Shell we put the label to int64?

**Comment by purerosefallen** [comment]
@edo9300 why not a table? table can do anything

**Comment by edo9300** [comment]
@purerosefallen if a table can do anything, a function can do even more

**Comment by purerosefallen** [comment]
@edo9300 `{f=function() ..... end}` ~~So a table is better~~

**Pull request merged**
