### PR TITLE
check Kaiser Colosseum in Duel.GetMZoneCount & Duel.GetLocationCountFromEx

### PR DESCRIPTION
**Pull request by purerosefallen**

### CODE REVIEW

**Review by salix5 — CHANGES_REQUESTED** [review]
cannot build

**Comment by purerosefallen** [comment]
~~fuck ChatGPT auto code~~

**Review by salix5 — APPROVED** [review]

**Review by salix5 — COMMENTED** [review]
If there is no EFFECT_KAISER_COLOSSEUM, the original function work as normal.
If there is, players who use Kaiser Colosseum should take full responsibilities for their behavior.

**Comment by mercury233** [comment]
I don't think we should care about this card any more since it is forbidden

**Pull request merged**
